### PR TITLE
[14.0][ADD] hr_expense_journal

### PR DESCRIPTION
**Pull request by Freni-SerpentCS**

### CODE REVIEW

**Review by dreispt — CHANGES_REQUESTED** [review]
Thank you Freni.
Please run pre-commit checks, and add the `readme/` subdirectory with the ducmentation fragments.

**Review by dreispt — APPROVED** [review]
Fixes added, functional tests made

**Comment by marcelsavegnago** [comment]
@Freni-SerpentCS How about including a field to determine which bank type journals can be selected when posting the expense?

Note: This is just a suggestion and if applicable, it will be implemented in the future.

**Review by marcelsavegnago — APPROVED** [review]

**Comment by dreispt** [comment]
@marcelsavegnago Sounds like a good idea, and indeed can be added as an improvement

**Pull request merged**
