### PR TITLE
[MIG] hr_expense_invoice: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by georginacicerchia** [comment]
Functional r+

**Review by MosabWadea — APPROVED** [review]
checked, please merge

**Comment by pedrobaeza** [comment]
/ocabot migration hr_expense_invoice

Please cherry-pick bde2af008bb40113593f2de57755055616ab8411

**Comment by MosabWadea** [comment]
Hello @nicomacr I have created a pull request in your fork to solve the requested change from Pedro
Please merge in your fork you allow this PR to merge

Thanks

**Comment by nicomacr** [comment]
> Hello @nicomacr I have created a pull request in your fork to solve the requested change from Pedro Please merge in your fork you allow this PR to merge
> 
> Thanks

Cherry pick ready in this PR

**Comment by nicomacr** [comment]
@pedrobaeza cherry pick https://github.com/OCA/hr-expense/commit/bde2af008bb40113593f2de57755055616ab8411 added in the PR

**Comment by MosabWadea** [comment]
hello @nicomacr 
I noticed an issue when I created an invoice from an expense the vendor bills are now getting wrong sequence-prefix value.
the prefix now is for one of the expenses already created, and any bill I create even manually are getting the same value.

below is the image of the expense report where I created the invoice:
image

below is a screenshot of the invoices list:
image

**Comment by MosabWadea** [comment]
I did some testing related to the problem mentioned earlier and I was able to point the issue:
so in version 14 when you click on the create vendor bill the module will create a draft bill with blank name:
image
image

but in version 15, it will create the bill and it will assign the name of the bill to be the same as the report:
image

and for some reason in version 15 the bill name can be edited in the external link wizard view:
image

so once the bill is confirmed, odoo will accept the bill name. and when a new bill is created for the same journal, odoo will look for the last bill name and compute the prefix value then it will create the new sequence!

to validate my troubleshooting, when a bill created, if I delete the name field manually before I confirm odoo will compute a serial number that is based on the last bill before the current.


I tried to fix this problem but I was not able to point where this issue is in the source code.

**Comment by MosabWadea** [comment]
Hello @pedrobaeza can you please advise on why this is happening and how to handle it?

**Comment by pedrobaeza** [comment]
Sorry, I don't know

**Comment by MosabWadea** [comment]
I did some debugging and testing and was able to find out that this only happens when the expense sheet is approved. not sure how or why this is causing this issue.
However, I did some fix and it worked for me and I created a PR at the fork of Mr. @nicomacr that I hope is a good way to fix it. 
What I did is that I added a line to manually set the name of the invoice to `/` to make sure it doesn't alter the invoices sequence.

referenced PR: https://github.com/adhoc-dev/hr-expense/pull/2

**Comment by nicomacr** [comment]
@pedrobaeza could you review the last changes?

**Pull request merged**
