### PR TITLE
[15.0][MIG]hr_expense_payment

### PR DESCRIPTION
**Pull request by manuelregidor**
Migration to 15.0.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
@pedrobaeza @ivantodorovich Do you mind validating this one? We need it in order to migrate hr_expense_cancel module.

THX!

**Review by ivantodorovich — APPROVED** [review]
LG

**Pull request merged**
