### PR TITLE
[13.0][MIG] hr_expense_portal: Migration to 13.0

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@dreispt  @rafaelbn  and @max3903 and @kittiu 

Can you please review this PR ?

**Comment by AmmarOfficewalaSerpentCS** [comment]
@pedrobaeza can you please review this PR?

**Comment by pedrobaeza** [comment]
Not using it, sorry.

**Review by dreispt — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Pull request merged**
