### PR TITLE
[14.0][FIX] hr_expense_payment: no create payments with paid by company

### PR DESCRIPTION
**Pull request by Saran440**
From pr: https://github.com/OCA/hr-expense/pull/14 I add create payment following odoo13 BUT odoo14 no need.

[BUG] 
- Accounting is wrong, when you paid by company. it will double lines.

Step to error:
1. Create expense paid by `company`
2. Submit to Manager -> Approve -> Post Journal Entries
    - Journal Entry on Expense will accounting:
        - Expenses Dr. 100
        - Outstanding Payments Cr. 100
Selection_005

    - Journal Entry on Payment will accounting:
        - Outstanding Payments Cr. 100
        - Account Payable Dr. 100
Selection_006

[FIX]
In standard odoo is correct (no create payment). This PR is delete create payment on paid by company following standard.

### CODE REVIEW

**Comment by Saran440** [comment]
@HaraldPanten @kittiu Hi, Please could you help review?
This PR will have an impact on the account.

**Comment by kittiu** [comment]
LGTM, back to good old one.

**Review by kittiu — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
Yes, this one is correct and it's needed

**Comment by HaraldPanten** [comment]
@pedrobaeza could you merge, please?

If we don't use this one, there'll be always some "orphan" payments pending to be reconciled.

THX!

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
> @pedrobaeza could you merge, please?
> 
> If we don't use this one, there'll be always some "orphan" payments pending to be reconciled.
> 
> THX!

Yes we also found the previous one was problematic. This is the fix.

**Pull request merged**
