### PR TITLE
[14.0][MIG] hr_expense_cancel

### PR DESCRIPTION
**Pull request by Saran440**
In odoo v14  `hr_expense` used register payment same as `account_move`
so, I change some function following

- if you cancel expense sheet after register payment, it will unlink payment too. (v13 is cancel state)
- case : paid by company, I search payment for update expense_sheet_id by
`self.env["account.payment"].search([], order="id desc", limit=1)`
because core odoo don't have function to hook. I'm not sure that we should overwrite function or search last payment
if you have any suggestion please let me know.

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional test. LGTM

**Comment by dsolanki-initos** [comment]
@Saran440  please Squash the last commit.

**Comment by dsolanki-initos** [comment]
Hi @Saran440 
Can you please squash the commit and ask the PSC team member to merge the PR?

**Comment by dsolanki-initos** [comment]
@OCA/human-resources-maintainers can you please merge this PR?

**Pull request merged**
