### PR TITLE
[ADD][14.0] hr_expense_advance_clearing_detail

### PR DESCRIPTION
**Pull request by Saran440**
This module allows to add/show details on employee advance and clearing

Depend on
- [x] hr_expense_advance_clearing - https://github.com/OCA/hr-expense/pull/25

### CODE REVIEW

**Comment by kittiu** [comment]
PR title, hr_expense_advnace_clearing_detail -> hr_expense_advance_clearing_detail

**Comment by kittiu** [comment]
@Saran440 please clear travis.

**Comment by kittiu** [comment]
ping @Saran440

**Comment by Saran440** [comment]
It's error from pre-commit cache.

`Error: reserveCache failed: Cache already exists. Scope: refs/pull/26/merge, Key: pre-commit-2-b0a5bffca046e57a4e8ba1313dc5edea302ab8f7dec6bc921412e0d9d194afe5-2d3526b39e77b192343b67e112d62afdf52fee9016f8d2d05199e444a70e4355, Version: 28cdb9f5496f334116f23e86f0063f5d3a9348c2e22425a33171e071aadada7e`

**Comment by kittiu** [comment]
Detail is not filled in Clearing if I create Clearing (hr.expense.sheet) directly, and then choose the Clear Advance.
**Note:** only if Clearing is created from Advance, the expense_line_ids will be filled correct.

**Test step:**

image

I don't create Clearing from Advance, but I create the Clearing directly and choose the Clear Advance.

image

1. Choose Clear Advance
2. Detail is listed
3. But the Expense is blank

**Comment by kittiu** [comment]
@Saran440 I will try fix this in another commit.

**Comment by kittiu** [comment]
@Saran440 please test the latest commit.

- [X] Fix test script
- [ ] Bug fix https://github.com/OCA/hr-expense/pull/43

**Comment by kittiu** [comment]
@Saran440 my intention is to use this PR https://github.com/OCA/hr-expense/pull/45 and we will no longer need this advance detail (because advance itself will be the detail).

This should remove complexity of maintaining many extension modules.

**Comment by Saran440** [comment]
move on hr_expense_advance_clearing https://github.com/OCA/hr-expense/pull/45

**Pull request closed without merging**
