### PR TITLE
[14.0][ENH] hr_expense_cancel : cancellation policy on expense

### PR DESCRIPTION
**Pull request by Saran440**
Currently, this module will delete Payment and Journal Entries,
when we click `cancel` after register payment on expense sheet.
it will be an issue accounting because sequence of account move is gone.

I propose that this module be enhanced such that the cancellation policy may be configured as follows:
1. you can configured cancellation policy on menu *Expenses > Configuration > Expenses > Expenses Cancellation Policy*
Selection_001
    - Policy: How to do with Journal Entry when you click cancel on Expense Report
        - Unlink - Delete Journal Entry
        - Cancel - Change state Journal Entry to cancel
    - State: State Expense Sheet that you need after click cancel
2. click cancel button on Expense Report
    - state paid - Can't visible button. you must have to cancel Payment and it will change state to Posted (process similar Vendor Bills > Vendor Payment)
    - state post - Cancel from (1.1) and state change to (1.2)

This PR implement depend on
- [x] hr_expense_payment https://github.com/OCA/hr-expense/pull/55

Reference
https://github.com/OCA/hr-expense/issues/88

### CODE REVIEW

**Comment by Saran440** [comment]
it's my concept for this module `hr_expense_cancel`.
flow_exp_cancel

if any idea, please suggest me.

**Comment by nimarosa** [comment]
Travis is failing, can you check why?

**Comment by kittiu** [comment]
@Saran440 can you check this error?

File "/home/travis/odoo-14.0/addons/account_edi/models/account_move.py", line 383, in button_draft
res = super().button_draft()
File "/home/travis/odoo-14.0/addons/account/models/account_move.py", line 2800, in button_draft
raise UserError(_('You cannot modify a posted entry of this journal because it is in strict mode.'))
odoo.exceptions.UserError: You cannot modify a posted entry of this journal because it is in strict mode.

**Comment by nimarosa** [comment]
@Saran440 Is this ready or you are still making changes to it?

**Review by nimarosa — APPROVED** [review]

**Comment by Saran440** [comment]
@nimarosa Functional is ready but i will change description or word in new field.
@kittiu can you help me change word to easy  understand?

**Comment by Saran440** [comment]
We will add this flow in version15 -> https://github.com/OCA/hr-expense/pull/167

**Pull request closed without merging**
