### PR TITLE
[16.0][MIG] hr_expense_advance_clearing

### PR DESCRIPTION
**Pull request by Saran440**
This PR enhance code to support hr_expense in version 16

Depend on:
- [x] https://github.com/OCA/hr-expense/pull/205

### CODE REVIEW

**Comment by Saran440** [comment]
This PR from https://github.com/OCA/hr-expense/pull/191

@jumeldi74 @LFPSGS
It already to review. can you check please?

**Review by rafaelbn — APPROVED** [review]
👍🏼

**Comment by rafaelbn** [comment]
Ping @OCA/human-resources-maintainers

**Comment by gjlong68** [comment]
image

**Comment by ps-tubtim** [comment]
**Step to test**

1. Create Employee Advance with $ 400.00
Selection_048

2. Create Clearing with $ 720.00 (Clearing over Advance)
Selection_049

I think the journal items of Clearing are incorrect, causing the journal items to be stuck, and waiting to be matched.

Selection_047
Selection_050

**Comment by Saran440** [comment]
@ps-tubtim Thank you for your reviewed. I fixed it, Can you recheck please?

@gjlong68 I'm not sure what's wrong please explain step to error.

**Comment by gjlong68** [comment]
Rechecked,it's ok,THK!




郭Sir
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OCA/hr-expense"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月24日(星期五) 中午11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OCA/hr-expense] [16.0][MIG] hr_expense_advance_clearing (PR #203)





 
@ps-tubtim Thank you for your reviewed. I fixed it, Can you recheck please?
 
@gjlong68 I'm not sure what's wrong please explain step to error.

**Review by ps-tubtim — APPROVED** [review]
Functional Test: Ok.

**Pull request merged**
