### PR TITLE
[14.0][IMP] hr_expense_invoice: prepare invoice values

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago @douglascstd @WesleyOliveira98 

The purpose of this PR is to separate the invoice values for use in a _prepare method. In cases where modifications are made to specific move_line only, it would be necessary to rewrite a significant amount of code. Therefore, using _prepare would facilitate this process.

### CODE REVIEW

**Comment by kaynnan** [comment]
@pedrobaeza, Can you review please?

**Review by pedrobaeza — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Review by mileo — APPROVED** [review]

**Review by mileo — CHANGES_REQUESTED** [review]
Could you create a prepare_invoice_line_values too?

**Comment by kaynnan** [comment]
> Could you create a prepare_invoice_line_values too?

Change implemented. Thank you for the suggestion, @mileo.

**Review by mileo — APPROVED** [review]

**Review by rvalyi — APPROVED** [review]

**Comment by kaynnan** [comment]
@pedrobaeza Do I need to do a rebase for the merge to occur? Apparently the bot didn't return something

**Pull request merged**
