### PR TITLE
[14.0][ADD] hr_expense_due_date: new module

### PR DESCRIPTION
**Pull request by kaynnan**
[HT00774]

cc @marcelsavegnago @WesleyOliveira98 @douglascstd 

This module allows defining due dates in `hr.expense.sheet`, either by specifying a fixed date or using a payment term.

### CODE REVIEW

**Comment by kaynnan** [comment]
ping @OCA/human-resources-maintainers

**Review by dreispt — APPROVED** [review]

**Review by WesleyOliveira98 — APPROVED** [review]
[FUNCTIONAL REVIEW]

Create an expense sheet and set a due date
image

The due date is defined in the journal item
image

Create another expense sheet and set an payment term as due date
image

The due date on the journal item will be calculated by the payment term
image

LGTM!

**Review by marcelsavegnago — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
Code Review :+1:

**Pull request merged**
