### PR TITLE
[14.0][FIX] hr_expense_advance_clearing: do not allow cancel PV related clearing or return

### PR DESCRIPTION
**Pull request by Saran440**
Payment on advance shouldn't cancel if it related clearing or return advance

Step to test:
1. Create advance 100 $ and normal process until paid (it will create 1 payment)
2. Clearing or return partial advance (20 $) : Clearing Residual = 80 $
3. Go to vendor payment > select payment related from advance (1)
4. reset to draft > cancel **(it shouldn't cancel this payment)**

This PR will check and not allow cancel if clearing residual is not equal amount payment
@kittiu

### CODE REVIEW

**Comment by Saran440** [comment]
@kittiu

**Comment by kittiu** [comment]
@Saran440 I change it to also cover cases clicking "Set Draft", "Cancel" and "Reverse".
Please review / approve.

**Review by ps-tubtim — APPROVED** [review]
LGTM.

**Review by kittiu — APPROVED** [review]

**Pull request merged**
