### PR TITLE
[16.0][MIG] hr_expense_cancel: Migration to version 16.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT43224

This PR superseeds https://github.com/OCA/hr-expense/pull/184

@victoralmau please review!

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@stefan-tecnativa I wonder why this module depends on `hr_expense_payment`. Can you tell me?

**Comment by stefan-tecnativa** [comment]
> @stefan-tecnativa I wonder why this module depends on `hr_expense_payment`. Can you tell me?

The module `hr_expense_payment` function is to link the generated payments with it's corresponding expense sheet. So when you want to cancel payments associated to a expense_sheet, you need to know which payments are related with your expense sheet. And that information is not available by inheriting `hr_expense` alone, we need the module

**Comment by pedrobaeza** [comment]
Thanks for the explanations. Please review https://github.com/OCA/hr-expense/pull/155 for merging it, and when done, please rebase here, remove the dependency, and put that explanation as a comment before declaring the dependency on the manifest.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump
/ocabot migration hr_expense_cancel

**Comment by em230418** [comment]
> /ocabot merge nobump
> /ocabot migration hr_expense_cancel

Hi, @pedrobaeza! Could you or your colleagues fix failing test on hr_expense_cancel, please? Otherwise every PR on 16.0 will be marked as failing. Here are examples:
https://github.com/OCA/hr-expense/pull/195
https://github.com/OCA/hr-expense/pull/191

**Comment by pedrobaeza** [comment]
`hr_expense_advance_clearing` tests are failing too, that belongs to the PR you mention, so there should be something changed upstream that makes them to fail. We are not able right now to check them. Maybe you could?

**Comment by Saran440** [comment]
@em230418 fixed it on pr https://github.com/OCA/hr-expense/pull/205

**Pull request merged**
