### PR TITLE
16.0 [MIG] hr_expense_payment: Migration to 16.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
@qrtl

### CODE REVIEW

**Comment by nimarosa** [comment]
@AungKoKoLin1997 Please rebase the PR to see if pre-commit errors are fixed in the 16.0 branch.

**Review by Yadier-Tecnativa — APPROVED** [review]
LGTM  TT43225

**Review by stefan-tecnativa — APPROVED** [review]
LGTM

**Comment by sbidoul** [comment]
@pedrobaeza can you retry? Maybe one command at a time (I'm not sure the bot supports multiple commands at once).

**Comment by pedrobaeza** [comment]
I have done it a lot of times, so yes, it's supported, but no problem:

/ocabot migration hr_expense_payment

**Pull request merged**
