### PR TITLE
[14.0][ADD] hr_expense_substate

### PR DESCRIPTION
**Pull request by ps-tubtim**
This module allows adding a substate to the expense report.

For each expense report state, you can define a substate. We this module you can define substate which allows you to extend the expense report workflow.

For example, you can add substate "To Verify" if the order can not be approved without the document checked and verified

Depends
- [x] https://github.com/OCA/server-ux/pull/366

### CODE REVIEW

**Comment by newtratip** [comment]
Please explain what do you do and add depend on module `base_substate` https://github.com/OCA/server-ux/pull/366 (This module still be in PR)

**Comment by ps-tubtim** [comment]
> Please explain what do you do and add depend on module `base_substate` [OCA/server-ux#366](https://github.com/OCA/server-ux/pull/366) (This module still be in PR)

@newtratip I already update. Thank you for your suggestion.

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by nimarosa** [comment]
LGTM

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Tested it, functional test is okay. Checks passing. Merging.

/ocabot merge nobump

**Pull request merged**
