### PR TITLE
[15.0][MIG] hr_expense_advance_clearing_sequence 

### PR DESCRIPTION
**Pull request by TheerayutEncoder**
Standard migration

### CODE REVIEW

**Comment by ps-tubtim** [comment]
@TheerayutEncoder Please separate the commits following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 and add you to CONTRIBUTORS.rst.

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
