### PR TITLE
[14.0][MIG] hr_expense_portal : Migrated to 14.0

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@dreispt , @rafaelbn , @max3903 and @kittiu 

Can you please review this PR ?

**Comment by AmmarOfficewalaSerpentCS** [comment]
@pedrobaeza  can you please review this PR ?

**Comment by pedrobaeza** [comment]
Not using it, sorry.

**Comment by AmmarOfficewalaSerpentCS** [comment]
> Not using it, sorry.

Sorry, I am not understood your answer

**Comment by pedrobaeza** [comment]
I don't use the module and not going to review it.

**Comment by AmmarOfficewalaSerpentCS** [comment]
Sorry, 
I saw your tweet related to **_#hacktoberfest_**  that's why I was ping you

**Comment by pedrobaeza** [comment]
The tweet is for labeling your pull request as valid for Hacktoberfest (as I have done now), not for reviewing it.

**Review by dreispt — APPROVED** [review]

**Pull request closed without merging**
