### PR TITLE
[14.0][FIX] hr_expense_advance_clearing, fix access right on .read()

### PR DESCRIPTION
**Pull request by kittiu**
Fix access right error on using sudo().read()

cc @Saran440

### CODE REVIEW

**Comment by Saran440** [comment]
@kittiu Could you add `clearing_residual` on tree view `hr.expense.report` for this pr?
I think it will helpful information.

`<field name="clearing_residual" optional="show" sum="Total Clearing Residual" decoration-bf="True"/>`


Selection_002

**Comment by kittiu** [comment]
> @kittiu Could you add `clearing_residual` on tree view `hr.expense.report` for this pr?
> I think it will helpful information.

Done

**Pull request merged**
