### PR TITLE
[17.0][MIG] hr_expense_advance_clearing

### PR DESCRIPTION
**Pull request by hongquangminh**
Module migrated to version 17.0

#214

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

Please also check the red CIs.

**Comment by Saran440** [comment]
@hongquangminh Hi, Thank you for your contribution.
I think you forgot to use `git format-patch` before migrating. The history should be shown in this PR.

However, we use this module in our project. May I migrate it instead of you (I am starting the migration to version 17)? Could you help us review it, please?

**Comment by hongquangminh** [comment]
> @hongquangminh Hi, Thank you for your contribution. I think you forgot to use `git format-patch` before migrating. The history should be shown in this PR.
> 
> However, we use this module in our project. May I migrate it instead of you (I am starting the migration to version 17)? Could you help us review it, please?

Hi @Saran440 , yes please, because I need this module for my business in version 17. And I don't see any migrated PR in this Repo. So that is why I am pushing this PR for official review. As you suggested, I will close this PR and wait for your session. Please ping me if you need to. Thanks!

**Pull request closed without merging**
