### PR TITLE
[17.0][MIG] hr_expense_payment: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 148967

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

Issue: https://github.com/OCA/hr-expense/issues/214

### CODE REVIEW

**Review by miquelpascual — APPROVED** [review]
Works correctly, checked in runboat

**Comment by peluko00** [comment]
@Saran440 Please review

**Review by lbarry-apsl — APPROVED** [review]
Works, tested on Runboat

**Review by yankinmax — APPROVED** [review]

**Pull request merged**
