### PR TITLE
[14.0][IMP] hr_expense_advance_cleaing: show advance on employee view

### PR DESCRIPTION
**Pull request by Saran440**
- Add advance tab on employee
Selection_001

- Add amount to clear on tree view expense report, it helpful user to find amount residual
Selection_002

### CODE REVIEW

**Comment by pedrobaeza** [comment]
On the employee form, instead of a new tab that makes to load the form slower, you should use an smart-button as common technique for linking things.

**Comment by Saran440** [comment]
okay, it's make sense. thanks :)

**Comment by albariera** [comment]
Could the button be invisible when the advance count is 0?

**Comment by Saran440** [comment]
@albariera Fixed.

**Review by albariera — APPROVED** [review]
Functional and technical review LGTM :+1:

**Review by kittiu — APPROVED** [review]

**Pull request merged**
