### PR TITLE
[14.0][MIG] hr_expense_invoice

### PR DESCRIPTION
**Pull request by aphon61bank**
Standard migration.

### CODE REVIEW

**Comment by yboujraf** [comment]
Anybody could check the PR please

**Comment by Saran440** [comment]
@yboujraf I think this module is not necessary migrate to v14
because core odoo create invoice when you post journal entries on expense.

**Comment by kittiu** [comment]
@Saran440 so, can you close this?

**Comment by pedrobaeza** [comment]
What happen if the invoice is already created. Can you link it?

**Comment by Saran440** [comment]
@pedrobaeza when you Post Journal Entries on Expense,
it will create Journal Entry and link on your expense.
Selection_001

**Comment by pedrobaeza** [comment]
But the utility of this module is to link an already created invoice. Take into account that you have different flows for receiving vendor bills than for receiving expenses. Imagine you receive a vendor bill by mail in your fetchmail gateway. A new move is created from it, and your accounting department fill data and validate it. Then your salesman sends the expense. You don't want that posting such expense will lead again to generate another vendor bill. This module should allow to fill the gap linking the existing vendor bill, and avoiding the generation of a new one.

**Comment by Saran440** [comment]
@pedrobaeza Okay, I see. this module still helpful.

@yboujraf This PR is no response and I will migrate it when I have a time
or Could you help me migrate to v14?

**Comment by yboujraf** [comment]
Dear @Saran440 

Mr @pedrobaeza explained clearly the use case.

Let me know what you expect from me.

Best Regards,

**Comment by Saran440** [comment]
@yboujraf I migrated to v14 with PR https://github.com/OCA/hr-expense/pull/51
Could you help review please?


Move on this PR to https://github.com/OCA/hr-expense/pull/51

**Pull request closed without merging**
