### PR TITLE
[14.0][ADD] hr_expense_pay_to_vendor

### PR DESCRIPTION
**Pull request by kittiu**
This module allow expense "Pay to Vendor" as option when user select, Paid By Company.

**Pay to Vendor** is suitable for cases when user wanted to buy something, i.e., Plane Ticket,
but do not want to pay money him/herself and use expense as the way to make payment order to accounting department.

When expense has posted journal entry, the AR will be set to Vendor (and not the Employee).
Then, register the payment will be clearing the AR to Bank.

image

TODO:

- [x] Test

### CODE REVIEW

**Comment by kittiu** [comment]
@peerayaproud this works ok?

**Comment by kittiu** [comment]
@Saran440 this PR works? Can you help review please.

**Comment by nimarosa** [comment]
Hello @kittiu is this ready or you have more changes to do? I test it later and we can merge if everything okay. Seems an interesting module.

**Comment by kittiu** [comment]
> Hello @kittiu is this ready or you have more changes to do? I test it later and we can merge if everything okay. Seems an interesting module.

Yes done. We been using it for a while.

**Pull request merged**
