### PR TITLE
[14.0][MIG] hr_expense_advance_clearing

### PR DESCRIPTION
**Pull request by Saran440**
Standard functional and Code update following

- Used register payment with Invoicing
- Avoid UserError from core odoo (default_get) by change account type to receivable and rollback.
- Update readme / test script.
~~Cherry-Pick from https://github.com/OCA/hr-expense/pull/24~~

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
Code review and Functional tests. LGTM

**Comment by dsolanki-initos** [comment]
Can someone please review the PR?

**Comment by dsolanki-initos** [comment]
@OCA/human-resources-maintainers can this be merged?

**Comment by Saran440** [comment]
@kittiu Could you help review this PR, Thank you.

**Pull request merged**
