### PR TITLE
[16.0][FIX] hr_expense_cancel: Adjust test to product w/o cost behavior

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please explain why this is needed.

**Comment by Saran440** [comment]
@pedrobaeza because demo product is no cost. In standard expense if no cost you can add amount total only.
Selection_011
Selection_012

**Comment by pedrobaeza** [comment]
Weird behavior they have put... Anyway, please add this explanation in the commit message in following lines, and use a better first line commit message:

```
[FIX] hr_expense_cancel: Adjust test to product w/o cost behavior

In this version, if a product doesn't have cost, you are only able
to enter total amount, so the test should be adjusted to this
condition.
```

**Review by em230418 — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
