### PR TITLE
[13.0][MIG] hr_expense_tier_validation

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]
Code LGTM.

**Comment by pegonzalezspesol** [comment]
LGTM. Code and some functional tests.

**Comment by Saran440** [comment]
@pegonzalezspesol Thank you for your review. Please can you approve this pr?

**Review by pegonzalezspesol — APPROVED** [review]
LGTM

**Pull request merged**
