### PR TITLE
[15.0][MIG] hr_expense_journal

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Comment by yboujraf** [comment]
Dear @Saran440  Don't know how to help for fixing those errors 

Best Regards,

**Comment by Saran440** [comment]
@yboujraf It still red because test script is not cover. you can help me to add test script and push it to this PR.

**Comment by yboujraf** [comment]
Dear @Saran440 
Never done but if you tell me where I will double check it.

Best Regards,

**Comment by Saran440** [comment]
@yboujraf Fixed, can you check it again please?

**Comment by yboujraf** [comment]
Is anyone could merge it ?

**Comment by yboujraf** [comment]
Dear @Saran440 

I have installed the hr_expense_journal on my dev platform and

image

Will wait for the merge

Thanks again

**Comment by yboujraf** [comment]
Anybody could merge the migration ?

**Comment by yboujraf** [comment]
Dear @Saran440 
Who could merge the migration ?
I am still using the migration branch. I am expecting to use from branch 15.0.
BR

**Comment by yboujraf** [comment]
@Saran440 , @Freni-OSI 
Pls, Anyone could merge this repo ?
BR

**Comment by Saran440** [comment]
@yboujraf if you're tested and it work. Could you approve this PR please?

**Comment by yboujraf** [comment]
Dear @Saran440 

I confirm the PR is working for V15.0. Please would you like to merge.

Best Regards,
Youssef

**Comment by Saran440** [comment]
@yboujraf
we need 2 person approved for merge.

May be you please approved this PR by
go to Files changed > Review changes > Approve
Selection_008
Selection_009

**Review by yboujraf — APPROVED** [review]
Dear @Saran440 

The migration for 15.0 is working fine and could be merged

Best Regards
Youssef

**Comment by yboujraf** [comment]
Dear

Done. Hope to use the released version soon and pls take a look for migration to 16.0 as well.

Best Regards
Youssef
________________________________

**Review by ps-tubtim — APPROVED** [review]

**Comment by yboujraf** [comment]
Dear @Saran440 

Could you check why "runboat/build" is pending ?

Best Regards

**Pull request merged**
