### PR TITLE
[14.0][FIX] hr_expense_advance_clearing: search for the property_account_expense_id considering the company in the hr.expense.sheet

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Search for the property_account_expense_id considering the company in the hr.expense.sheet

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @OCA/human-resources-maintainers

**Comment by marcelsavegnago** [comment]
ping @kittiu

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Review by rvalyi — APPROVED** [review]

**Review by kaynnan — APPROVED** [review]

**Pull request merged**
