### PR TITLE
[17.0][MIG] hr_expense_employee_analytic_default: Migration to 17.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 17.0

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT50068

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Maybe the module should be renamed to something like hr_expense_employee_analytic_distribution?

**Comment by victoralmau** [comment]
I agree that the current name is not the right one, maybe `hr_expense_employee_analytic_distribution_default`?

What do you think @pedrobaeza ?

**Review by pedrobaeza — APPROVED** [review]
I think it's OK to keep the name, as there's no better one.

/ocabot migration hr_expense_employee_analytic_default

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
