### PR TITLE
[14.0][ADD] hr_expense_work_acceptance

### PR DESCRIPTION
**Pull request by kittiu**
This module extend purchase work acceptance and add option to create work acceptance from expense report.

- [x] Test

### CODE REVIEW

**Comment by kittiu** [comment]
cc @Saran440 @ps-tubtim @newtratip

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
@Saran440 @kittiu pre-commit is failing in merge. Can you check it and we try again?

**Comment by Saran440** [comment]
waiting https://github.com/OCA/hr-expense/pull/147 merge

**Comment by nimarosa** [comment]
> waiting https://github.com/OCA/hr-expense/pull/147 merge

@Saran440 that PR is closed. is this PR ready?

**Comment by Saran440** [comment]
@nimarosa yes, this's ready to merge. move on https://github.com/OCA/hr-expense/pull/147 to https://github.com/OCA/hr-expense/pull/148

sorry for not updated

**Pull request merged**
