### PR TITLE
[14.0][MIG] hr_expense_advance_clearing_consolidation: Migration to 14.0

### PR DESCRIPTION
**Pull request by rodrigonevest**
cc/ @marcelsavegnago @kaynnan @Saran440 @douglascstd

### CODE REVIEW

**Review by WesleyOliveira98 — APPROVED** [review]
[FUNCTIONAL AND CODE TEST]

Create two advances with status paid and an amount to clear
image

Select the two advances, click in the Action button and then click on Consolidate Open Advances option.
image

It's generated one consolidated advance with the total ammount
image

And it's created the Write Off lines for the account.move.line reconciliation
image

LGTM!

**Review by kaynnan — CHANGES_REQUESTED** [review]
@WesleyOliveira98 I understand that there were new changes for the module to work correctly in v14, but the changes made to the FIX commit must be in the MIG commit.

**Comment by marcelsavegnago** [comment]
@douglascstd can you review please ?

**Review by kaynnan — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Pull request merged**
